%YAML 1.0
---
shelf_z_: -0.65
pot_height_: 0.22
voxel_grid_size_laser_: 0.001
normal_estimation_radius_: 0.005
region_grow_residual_threshold_: 0.01
region_grow_smoothness_threshold_: 7.0
region_grow_curvature_threshold_: 20.0
region_grow_num_neighbors_: 8
region_grow_min_cluster_size_:1000
region_grow_max_cluster_size_:100000
laser_scan_frequency_: 2000.0
scan_speed_: 0.1
scan_acceleration_: 0.2
move_arm_speed_: 0.1
move_arm_acceleration_: 0.05
move_joint_speed_: 0.5
move_joint_acceleration_: 0.2
seed_resolution_: 0.05
spatial_importance_: 0.5
normal_importance_: 1.0
sor_mean_k_: 15
sor_std_: 1.0
ror_radius_: 0.005
ror_num_: 10
hyperspectral_imaging_dist_: 0.265
max_samples_per_leaf_: 2
max_samples_per_plant_: 2
probe_patch_max_curvature_: 0.01
probing_patch_rmse_: 0.1
hyperscan_slice_thickness_: 0.01
enable_path_planning_: 1
vis_z_range_: 1.5
enable_thermo_: 1
enable_tof_: 1
enable_rgb_ : 1
enable_hyperspectral_: 1
enable_scanner_: 1
enable_arm_: 1
enable_probing_: 1
remap_pot_position_: 0
only_do_probing_ : 0
view_time_: 50
multi_work_position_: 1
hyperspectral_topview_: 1
leaf_tracing_hyperspectral_: 1
enable_imaging_: 1
upload_data_: 0
start_time_: "11:20"
scheduled_minutes_per_chamber_: 50
sideview_camera_x_pos_ : 0.77
close_door_when_rover_inside_: 0