%YAML 1.0
---
shelf_z_: -0.6
voxel_grid_size_laser_: 0.001
normal_estimation_radius_: 0.005
region_grow_residual_threshold_: 0.01
region_grow_smoothness_threshold_: 7.0
region_grow_curvature_threshold_: 20.0
region_grow_num_neighbors_: 8
region_grow_min_cluster_size_:1000
region_grow_max_cluster_size_:10000
laser_scan_frequency_: 2000.0
scan_speed_: 0.1
scan_acceleration_: 0.5
move_arm_speed_: 0.1 
move_arm_acceleration_: 0.1
move_joint_speed_: 0.5
move_joint_acceleration_: 0.2
seed_resolution_: 0.1
spatial_importance_: 0.5
normal_importance_: 1.0
sor_mean_k_: 15
sor_std_: 1.0
ror_radius_: 0.005
ror_num_: 10
num_plants_: 14
hyperspectral_imaging_dist_: 0.18
max_samples_per_leaf_: 4
probing_patch_rmse_: 0.1
hyperscan_slice_thickness_: 0.01
enable_probing_: 0
enable_path_planning_: 1
vis_z_range_: 0.5
remap_pot_position_: 0
cur_chamber_id_: 6
only_do_probing_ : 1
view_time_: 100
multi_work_position_: 0